# http://docs.ansible.com/ansible/latest/playbooks_best_practices.html#directory-layout
---

- hosts: all
  connection: local
  gather_facts: true
  become: true
  become_user: "root"
  vars_files:
    - "vars.yml"
  roles:
    - nodejs
